import {createHash,randomUUID} from "node:crypto";
import {readFile} from "node:fs/promises";
import {expect,test,type Page,type APIRequestContext} from "@playwright/test";
const password=process.env.HESTIA_TEST_PASSWORD;
if(!password||process.env.HESTIA_ENVIRONMENT!=="local")throw new Error("Use the owned synthetic E2E harness.");
async function login(page:Page,member="camille"){
  await page.goto("/");
  for(let i=0;i<4;i++){await page.getByLabel("Adresse e-mail").fill(`${member}@hestia.invalid`);await page.getByLabel("Mot de passe",{exact:true}).fill(password!);const pending=page.waitForResponse(r=>r.url().endsWith("/api/auth/sign-in/email"));await page.getByRole("button",{name:"Se connecter",exact:true}).click();const response=await pending;if(response.status()!==429){expect(response.status()).toBe(200);break;}await page.waitForTimeout(10_100);}
  await expect(page.getByRole("heading",{name:"Dossiers",exact:true})).toBeVisible();
}
async function create(api:APIRequestContext,name:string,parentId:string|null=null){const r=await api.post("/api/hestia/folders",{headers:{Origin:"http://127.0.0.1:3210"},data:{name,parentId,idempotencyKey:randomUUID()}});expect(r.status()).toBe(201);return (await r.json()).folder as {id:string;name:string;version:number};}
async function openRoot(page:Page,name:string){await page.reload();await page.getByRole("main").getByRole("button",{name:new RegExp(name)}).click();await expect(page.getByRole("heading",{name,exact:true})).toBeVisible();}

test("sous-dossiers, collision neutre, chemin profond et renommage au clavier",async({page,isMobile})=>{
  await login(page);const suffix=randomUUID().slice(0,8);const root=await create(page.request,`Arbre ${suffix}`);
  const child=await create(page.request,"Factures",root.id);let parent=child;for(let i=0;i<12;i++)parent=await create(page.request,`Niveau ${i+1} ${suffix}`,parent.id);
  await openRoot(page,root.name);
  await page.getByRole("button",{name:"Nouveau sous-dossier",exact:true}).click();const panel=page.getByRole("complementary",{name:"Nouveau sous-dossier",exact:true});
  await expect(panel.getByText(/aucun droit n’est ajouté/)).toBeVisible();await panel.getByLabel("Nom du dossier").fill(" factures ");await panel.getByRole("button",{name:"Créer le dossier",exact:true}).click();await expect(panel.getByRole("alert")).toContainText("Ce nom n’est pas disponible");await panel.getByRole("button",{name:"Annuler",exact:true}).click();
  await page.getByRole("main").getByRole("button",{name:/Factures/}).click();for(let i=0;i<12;i++)await page.getByRole("main").getByRole("button",{name:new RegExp(`Niveau ${i+1} ${suffix}`)}).click();
  await expect(page.getByRole("heading",{name:parent.name,exact:true})).toBeVisible();
  await page.getByRole("button",{name:isMobile?/Afficher le chemin complet/:/Afficher les .* niveaux intermédiaires/}).click();await expect(page.getByRole("navigation",{name:"Chemin complet"})).toContainText(root.name);
  await page.getByRole("button",{name:"Actions",exact:true}).click();await expect(page.getByRole("menuitem",{name:"Renommer",exact:true})).toBeFocused();await page.keyboard.press("Enter");await page.getByLabel("Nom du dossier").fill(`Renommé ${suffix}`);await page.getByRole("button",{name:"Enregistrer le nom",exact:true}).click();await expect(page.getByRole("heading",{name:`Renommé ${suffix}`,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:test.info().outputPath("tree-deep.png"),fullPage:true});
});

test("réponse perdue après commit : vérifier avant réessai sans doublon",async({page})=>{
  await login(page);const name=`Unique ${randomUUID().slice(0,8)}`;let committed=false;let posted=0;
  await page.route("**/api/hestia/folders",async route=>{if(route.request().method()!=="POST")return route.continue();posted++;const response=await route.fetch();expect(response.status()).toBe(201);committed=true;await route.abort("failed");});
  await page.getByRole("button",{name:"Nouveau dossier",exact:true}).click();await page.getByLabel("Nom du dossier").fill(name);await page.getByRole("button",{name:"Créer le dossier",exact:true}).click();await expect(page.getByText("Résultat incertain.",{exact:true})).toBeVisible();expect(committed).toBe(true);await expect(page.getByRole("button",{name:"Créer le dossier",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Vérifier le résultat",exact:true}).click();await expect(page.getByRole("heading",{name,exact:true})).toBeVisible();expect(posted).toBe(1);const inventory=await(await page.request.get("/api/hestia/folders")).json();expect(inventory.folders.filter((f:{name:string})=>f.name===name)).toHaveLength(1);
});

test("partage isolé : aucun ancêtre privé, retrait connu retire la vue",async({page,browser})=>{
  await login(page);const suffix=randomUUID().slice(0,8);const root=await create(page.request,`Parent confidentiel ${suffix}`);const child=await create(page.request,`Partagé seul ${suffix}`,root.id);
  const sharing=await(await page.request.get(`/api/hestia/folders/${child.id}/sharing`)).json();const alex=sharing.members.find((m:{name:string})=>m.name==="Alex");expect(alex).toBeTruthy();expect((await page.request.post(`/api/hestia/folders/${child.id}/sharing`,{headers:{Origin:"http://127.0.0.1:3210"},data:{memberId:alex.id,export:false,deposit:false,modify:false,delete:false,idempotencyKey:randomUUID()}})).status()).toBe(200);
  const context=await browser.newContext({baseURL:"http://127.0.0.1:3210"});
  try{const receiver=await context.newPage();await login(receiver,"alex");const inventory=await(await receiver.request.get("/api/hestia/folders")).json();const row=inventory.folders.find((f:{id:string})=>f.id===child.id);expect(row.visibleParentId).toBeNull();expect(row.breadcrumbs).toEqual([{id:child.id,name:child.name}]);expect(JSON.stringify(inventory)).not.toContain(root.name);expect(JSON.stringify(inventory)).not.toContain(root.id);await receiver.getByRole("main").getByRole("button",{name:new RegExp(child.name)}).click();await expect(receiver.getByRole("heading",{name:child.name,exact:true})).toBeVisible();await expect(receiver.getByText(root.name,{exact:false})).toHaveCount(0);expect((await receiver.request.get(`/api/hestia/folders/${root.id}`)).status()).toBe(404);
    const access=await(await page.request.get(`/api/hestia/folders/${child.id}/access`)).json();const grant=access.grants.find((g:{memberId:string;canRevoke:boolean})=>g.memberId===alex.id&&g.canRevoke);expect(grant).toBeTruthy();expect((await page.request.delete(`/api/hestia/folders/${child.id}/access/${grant.id}`,{headers:{Origin:"http://127.0.0.1:3210"}})).status()).toBe(200);const freshInventory=receiver.waitForResponse(response=>response.url().endsWith("/api/hestia/folders")&&response.request().method()==="GET"&&response.status()===200);await receiver.bringToFront();await receiver.evaluate(()=>window.dispatchEvent(new Event("focus")));await freshInventory;await expect(receiver.getByRole("heading",{name:child.name,exact:true})).toHaveCount(0);try { await expect(receiver.getByText(child.name,{exact:false})).toHaveCount(0); } catch(error) { await test.info().attach("revoked-matching-nodes",{body:JSON.stringify({targetName:child.name,visibility:await receiver.evaluate(()=>({hidden:document.hidden,state:document.visibilityState})),nodes:await receiver.getByText(child.name,{exact:false}).evaluateAll(nodes=>nodes.map(node=>({tag:node.tagName,role:node.getAttribute("role"),classes:node.className,textLength:node.textContent?.length,ancestors:[node.parentElement,node.parentElement?.parentElement].filter(Boolean).map(parent=>({tag:parent!.tagName,role:parent!.getAttribute("role"),classes:parent!.className}))})))},null,2),contentType:"application/json"}); throw error; }expect((await receiver.request.get(`/api/hestia/folders/${child.id}`)).status()).toBe(404);
  }finally{await context.close();}
});

test("restriction ciblée puis levée : les autres capacités héritées demeurent",async({page})=>{
  await login(page);const suffix=randomUUID().slice(0,8);const root=await create(page.request,`Restriction ${suffix}`);const child=await create(page.request,`Branche ${suffix}`,root.id);
  const sharing=await(await page.request.get(`/api/hestia/folders/${root.id}/sharing`)).json();const alex=sharing.members.find((m:{name:string})=>m.name==="Alex");expect(alex).toBeTruthy();
  expect((await page.request.post(`/api/hestia/folders/${root.id}/sharing`,{headers:{Origin:"http://127.0.0.1:3210"},data:{memberId:alex.id,export:true,deposit:false,modify:true,delete:true,idempotencyKey:randomUUID()}})).status()).toBe(200);
  await openRoot(page,root.name);await page.getByRole("main").getByRole("button",{name:new RegExp(child.name)}).click();await page.getByRole("tab",{name:"Accès",exact:true}).click();await page.getByRole("tabpanel",{name:"Accès",exact:true}).getByRole("button",{name:/Alex/}).click();
  const person=page.getByRole("complementary",{name:"Alex",exact:true});await expect(person.getByText(/Hérité d’un dossier parent/)).toBeVisible();await person.getByRole("button",{name:"Restreindre ici…",exact:true}).click();
  const restriction=page.getByRole("complementary",{name:"Restreindre Alex ici",exact:true});await restriction.getByRole("checkbox",{name:"Supprimer",exact:true}).check();await restriction.getByRole("button",{name:"Restreindre",exact:true}).click();await expect(person.getByText("Restriction enregistrée.",{exact:true})).toBeVisible();
  let access=await(await page.request.get(`/api/hestia/folders/${child.id}/access`)).json();let rights=access.members.find((m:{id:string})=>m.id===alex.id).capabilities;expect(rights).toEqual(expect.arrayContaining(["consulter","modifier","exporter"]));expect(rights).not.toContain("supprimer");
  await person.getByRole("button",{name:"Lever la restriction",exact:true}).click();const dialog=page.getByRole("dialog");await expect(dialog).toContainText("Aucun accès révoqué ou expiré n’est rétabli");await dialog.getByRole("button",{name:"Lever la restriction",exact:true}).click();await expect(person.getByText("Restriction levée.",{exact:true})).toBeVisible();access=await(await page.request.get(`/api/hestia/folders/${child.id}/access`)).json();rights=access.members.find((m:{id:string})=>m.id===alex.id).capabilities;expect(rights).toEqual(expect.arrayContaining(["consulter","modifier","supprimer","exporter"]));
});

test("retrait pendant une saisie non soumise efface nom et panneau immédiatement",async({page,browser})=>{
  await login(page);const context=await browser.newContext({baseURL:"http://127.0.0.1:3210"});
  try{const receiver=await context.newPage();await login(receiver,"alex");
    for(const mode of ["rename","create"] as const){
      const suffix=randomUUID().slice(0,8);const root=await create(page.request,`Parent formulaire ${suffix}`);const child=await create(page.request,`Formulaire partagé ${suffix}`,root.id);const sharing=await(await page.request.get(`/api/hestia/folders/${child.id}/sharing`)).json();const alex=sharing.members.find((m:{name:string})=>m.name==="Alex");
      expect((await page.request.post(`/api/hestia/folders/${child.id}/sharing`,{headers:{Origin:"http://127.0.0.1:3210"},data:{memberId:alex.id,export:false,deposit:false,modify:true,delete:false,idempotencyKey:randomUUID()}})).status()).toBe(200);
      await receiver.reload();await receiver.getByRole("main").getByRole("button",{name:new RegExp(child.name)}).click();
      if(mode==="rename"){await receiver.getByRole("button",{name:"Actions",exact:true}).click();await receiver.getByRole("menuitem",{name:"Renommer",exact:true}).click();}else await receiver.getByRole("button",{name:"Nouveau sous-dossier",exact:true}).click();
      const draft=`Saisie privée ${suffix}`;await receiver.getByLabel("Nom du dossier").fill(draft);const access=await(await page.request.get(`/api/hestia/folders/${child.id}/access`)).json();const grant=access.grants.find((g:{memberId:string;canRevoke:boolean})=>g.memberId===alex.id&&g.canRevoke);expect(grant).toBeTruthy();expect((await page.request.delete(`/api/hestia/folders/${child.id}/access/${grant.id}`,{headers:{Origin:"http://127.0.0.1:3210"}})).status()).toBe(200);
      const fresh=receiver.waitForResponse(r=>r.url().endsWith("/api/hestia/folders")&&r.request().method()==="GET"&&r.status()===200);await receiver.bringToFront();await receiver.evaluate(()=>window.dispatchEvent(new Event("focus")));await fresh;
      await expect(receiver.getByLabel("Nom du dossier")).toHaveCount(0);expect(await receiver.locator("input").evaluateAll(inputs=>inputs.map(input=>(input as HTMLInputElement).value))).not.toContain(draft);await expect(receiver.getByRole("complementary",{name:mode==="rename"?"Renommer":"Nouveau sous-dossier",exact:true})).toHaveCount(0);await expect(receiver.getByText(child.name,{exact:false})).toHaveCount(0);
    }
  }finally{await context.close();}
});

test("retrait connu efface résultats de recherche et aperçu sans changer la saisie",async({page,browser,isMobile})=>{
  await login(page);const suffix=randomUUID().slice(0,8);const root=await create(page.request,`Parent recherche ${suffix}`);const child=await create(page.request,`Partage recherche ${suffix}`,root.id);const title=`Document révocable ${suffix}`;const fileName=`original-${suffix}.png`;const headers={Origin:"http://127.0.0.1:3210"};
  const bytes=await readFile("tests/fixtures/documents/synthetic.png");const start=await page.request.post("/api/hestia/uploads",{headers,data:{folderId:child.id,idempotencyKey:randomUUID(),fileName,title,size:bytes.length,mediaType:"image/png",sha256:createHash("sha256").update(bytes).digest("hex"),source:"import"}});expect(start.ok()).toBe(true);const {operation}=await start.json();expect((await page.request.put(`/api/hestia/uploads/${operation.id}/chunks/0`,{headers:{...headers,"Content-Type":"application/octet-stream"},data:bytes})).ok()).toBe(true);expect((await page.request.post(`/api/hestia/uploads/${operation.id}/complete`,{headers,data:{keepDuplicate:false}})).ok()).toBe(true);
  const sharing=await(await page.request.get(`/api/hestia/folders/${child.id}/sharing`)).json();const alex=sharing.members.find((m:{name:string})=>m.name==="Alex");expect((await page.request.post(`/api/hestia/folders/${child.id}/sharing`,{headers,data:{memberId:alex.id,export:false,deposit:false,modify:false,delete:false,idempotencyKey:randomUUID()}})).status()).toBe(200);
  const context=await browser.newContext({baseURL:"http://127.0.0.1:3210",viewport:page.viewportSize(),isMobile,hasTouch:isMobile});
  try{const receiver=await context.newPage();await login(receiver,"alex");const query=suffix;
    if(isMobile){await receiver.getByRole("button",{name:"Rechercher",exact:true}).click();await receiver.getByLabel("Rechercher",{exact:true}).fill(query);}else await receiver.getByLabel("Rechercher un document ou un dossier",{exact:true}).fill(query);
    await receiver.getByRole("main").getByRole("button",{name:new RegExp(title)}).click();const detail=receiver.getByRole("complementary",{name:"Document",exact:true});await expect(detail.getByRole("img",{name:`Aperçu de ${title}`})).toBeVisible();await expect(detail.getByText(fileName,{exact:true})).toBeVisible();
    const access=await(await page.request.get(`/api/hestia/folders/${child.id}/access`)).json();const grant=access.grants.find((g:{memberId:string;canRevoke:boolean})=>g.memberId===alex.id&&g.canRevoke);expect(grant).toBeTruthy();expect((await page.request.delete(`/api/hestia/folders/${child.id}/access/${grant.id}`,{headers})).status()).toBe(200);
    const fresh=receiver.waitForResponse(r=>r.url().endsWith("/api/hestia/folders")&&r.request().method()==="GET"&&r.status()===200);await receiver.bringToFront();await receiver.evaluate(()=>window.dispatchEvent(new Event("focus")));await fresh;
    await expect(receiver.getByLabel("Rechercher",{exact:true})).toHaveValue(query);await expect(receiver.getByText(title,{exact:false})).toHaveCount(0);await expect(receiver.getByText(fileName,{exact:false})).toHaveCount(0);await expect(detail).toHaveCount(0);await expect(receiver.locator('img[src^="blob:"],iframe[src^="blob:"],.h-preview canvas')).toHaveCount(0);await expect(receiver.getByText(child.name,{exact:false})).toHaveCount(0);
  }finally{await context.close();}
});
