import {createHash,randomUUID} from "node:crypto";
import {readFile} from "node:fs/promises";
import {test,expect,type Page,type APIRequestContext} from "@playwright/test";
const password=process.env.HESTIA_TEST_PASSWORD;
if(!password||process.env.HESTIA_ENVIRONMENT!=="local")throw new Error("Use the owned synthetic E2E harness.");
const headers={Origin:"http://127.0.0.1:3210"};
type Folder={id:string;name:string;version:number};
async function login(page:Page,member="camille"){
  await page.goto("/");for(let attempt=0;attempt<4;attempt++){
    await page.getByLabel("Adresse e-mail").fill(`${member}@hestia.invalid`);await page.getByLabel("Mot de passe",{exact:true}).fill(password!);
    const response=page.waitForResponse(result=>result.url().endsWith("/api/auth/sign-in/email"));await page.getByRole("button",{name:"Se connecter",exact:true}).click();const result=await response;
    if(result.status()!==429){expect(result.status()).toBe(200);break;}await page.waitForTimeout(10_100);
  }await expect(page.getByRole("heading",{name:"Dossiers",exact:true})).toBeVisible();
}
async function create(api:APIRequestContext,name:string,parentId:string|null=null):Promise<Folder>{const result=await api.post("/api/hestia/folders",{headers,data:{name,parentId,idempotencyKey:randomUUID()}});expect(result.status()).toBe(201);return(await result.json()).folder;}
async function open(page:Page,folder:Folder){await page.reload();await page.getByRole("main").getByRole("button",{name:new RegExp(folder.name)}).click();await expect(page.getByRole("heading",{name:folder.name,exact:true})).toBeVisible();}
async function start(page:Page){await page.getByRole("button",{name:"Actions",exact:true}).click();await page.getByRole("menuitem",{name:"Déplacer…",exact:true}).click();return page.getByRole("complementary",{name:/^Déplacer «/});}
async function pick(page:Page,destination:Folder){const panel=page.getByRole("complementary",{name:/^Déplacer «/});const up=panel.getByRole("button",{name:"Tous les dossiers",exact:true});if(await up.count())await up.click();await panel.getByRole("radio",{name:destination.name,exact:true}).click();await panel.getByRole("button",{name:"Vérifier les effets",exact:true}).click();return panel;}
async function tree(page:Page){await login(page);const suffix=randomUUID().slice(0,8);const source=await create(page.request,`Départ ${suffix}`),destination=await create(page.request,`Arrivée ${suffix}`);await open(page,source);return{source,destination,suffix};}
async function parent(api:APIRequestContext,id:string){const listing=await(await api.get("/api/hestia/folders")).json();return listing.folders.find((folder:{id:string})=>folder.id===id)?.visibleParentId;}
async function share(api:APIRequestContext,folder:Folder,memberId:string){expect((await api.post(`/api/hestia/folders/${folder.id}/sharing`,{headers,data:{memberId,export:false,deposit:false,modify:true,delete:false,idempotencyKey:randomUUID()}})).ok()).toBe(true);}
async function upload(api:APIRequestContext,folder:Folder,title:string){const bytes=await readFile("tests/fixtures/documents/synthetic.png");const response=await api.post("/api/hestia/uploads",{headers,data:{folderId:folder.id,idempotencyKey:randomUUID(),fileName:`${title}.png`,title,size:bytes.length,mediaType:"image/png",sha256:createHash("sha256").update(bytes).digest("hex"),source:"import"}});expect(response.ok()).toBe(true);const{operation}=await response.json();expect((await api.put(`/api/hestia/uploads/${operation.id}/chunks/0`,{headers:{...headers,"Content-Type":"application/octet-stream"},data:bytes})).ok()).toBe(true);expect((await api.post(`/api/hestia/uploads/${operation.id}/complete`,{headers,data:{keepDuplicate:false}})).ok()).toBe(true);const listing=await(await api.get(`/api/hestia/documents?folderId=${folder.id}`)).json();return listing.documents.find((doc:{title:string})=>doc.title===title) as {id:string;title:string};}
async function moveApi(api:APIRequestContext,kind:"folder"|"document",sourceId:string,destinationId:string|null){const body={kind,sourceId,destinationId};const preview=await api.post("/api/hestia/move-preview",{headers,data:body});expect(preview.ok()).toBe(true);const result=await preview.json();expect(result.allowed).toBe(true);expect((await api.post("/api/hestia/moves",{headers,data:{...body,previewToken:result.previewToken,idempotencyKey:randomUUID()}})).ok()).toBe(true);}

test("déplacer un sous-arbre au clavier, puis suivre son chemin sans toucher au contenu",async({page})=>{
  const{source,destination,suffix}=await tree(page);const child=await create(page.request,`Contenu ${suffix}`,source.id);await page.reload();await page.getByRole("main").getByRole("button",{name:new RegExp(source.name)}).click();
  const panel=await start(page);const radio=panel.getByRole("radio",{name:destination.name,exact:true});await radio.focus();await page.keyboard.press("Space");await expect(radio).toHaveAttribute("aria-checked","true");await page.screenshot({path:test.info().outputPath("move-picker.png"),fullPage:true});await panel.getByRole("button",{name:"Vérifier les effets"}).click();await expect(panel.getByText("Effets sur les accès",{exact:true})).toBeVisible();await expect(panel.getByText("La gestion et l’espace déjà compté ne changent pas.",{exact:true})).toBeVisible();await panel.getByRole("button",{name:"Déplacer ici",exact:true}).click();await expect(page.getByText("Déplacé.",{exact:true})).toBeVisible();expect(await parent(page.request,source.id)).toBe(destination.id);expect(await parent(page.request,child.id)).toBe(source.id);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath("move-complete.png"),fullPage:true});
});

test("déplacer un document conserve identité et original et ne propose aucune racine",async({page})=>{
  const{source,destination,suffix}=await tree(page);const bytes=await readFile("tests/fixtures/documents/synthetic.png"),hash=createHash("sha256").update(bytes).digest("hex"),title=`Original ${suffix}`;
  const uploaded=await page.request.post("/api/hestia/uploads",{headers,data:{folderId:source.id,idempotencyKey:randomUUID(),fileName:`original-${suffix}.png`,title,size:bytes.length,mediaType:"image/png",sha256:hash,source:"import"}});expect(uploaded.ok()).toBe(true);const{operation}=await uploaded.json();expect((await page.request.put(`/api/hestia/uploads/${operation.id}/chunks/0`,{headers:{...headers,"Content-Type":"application/octet-stream"},data:bytes})).ok()).toBe(true);expect((await page.request.post(`/api/hestia/uploads/${operation.id}/complete`,{headers,data:{keepDuplicate:false}})).ok()).toBe(true);
  const before=(await(await page.request.get(`/api/hestia/documents?folderId=${source.id}`)).json()).documents.find((doc:{title:string})=>doc.title===title);
  await open(page,source);await page.getByRole("main").getByRole("button",{name:new RegExp(title)}).click();await page.getByRole("complementary",{name:"Document",exact:true}).getByRole("button",{name:"Déplacer…",exact:true}).click();await expect(page.getByRole("complementary",{name:/^Déplacer «/}).getByRole("radio",{name:"À la racine (Dossiers)"})).toHaveCount(0);const panel=await pick(page,destination);await panel.getByRole("button",{name:"Déplacer ici",exact:true}).click();await expect(page.getByText("Déplacé.",{exact:true})).toBeVisible();const after=(await(await page.request.get(`/api/hestia/documents?folderId=${destination.id}`)).json()).documents.find((doc:{id:string})=>doc.id===before.id);expect(after).toMatchObject({id:before.id,sha256:hash,fileName:before.fileName,uploadedByName:before.uploadedByName,folderId:destination.id});
});

test("extraire à la racine refuse un sous-dossier sans gestion autonome",async({page})=>{
  const{source,suffix}=await tree(page);const child=await create(page.request,`Gestion héritée ${suffix}`,source.id);await page.reload();await page.getByRole("main").getByRole("button",{name:new RegExp(source.name)}).click();await page.getByRole("main").getByRole("button",{name:new RegExp(child.name)}).click();const panel=await start(page);await panel.getByRole("button",{name:"Tous les dossiers",exact:true}).click();await panel.getByRole("radio",{name:"À la racine (Dossiers)",exact:true}).click();await panel.getByRole("button",{name:"Vérifier les effets",exact:true}).click();await expect(panel.getByRole("alert")).toContainText(/gestion/i);await expect(panel.getByRole("button",{name:"Déplacer ici",exact:true})).toHaveCount(0);expect(await parent(page.request,child.id)).toBe(source.id);
});

test("collision : changer le nom impose un nouvel aperçu avant déplacement",async({page})=>{
  const{source,destination}=await tree(page);await create(page.request,source.name,destination.id);await start(page);const panel=await pick(page,destination);await expect(panel.getByText("Rien ne sera fusionné ni remplacé.")).toBeVisible();await panel.getByLabel(`Nouveau nom pour « ${source.name} »`).fill(`${source.name} bis`);await expect(panel.getByRole("button",{name:"Déplacer ici",exact:true})).toHaveCount(0);await panel.getByRole("button",{name:"Vérifier les effets",exact:true}).click();await panel.getByRole("button",{name:"Déplacer ici",exact:true}).click();await expect(page.getByRole("heading",{name:`${source.name} bis`,exact:true})).toBeVisible();expect(await parent(page.request,source.id)).toBe(destination.id);
});

test("aperçu périmé : aucun effet avant une nouvelle confirmation explicite",async({page})=>{
  const{source,destination}=await tree(page);await start(page);const panel=await pick(page,destination);
  const sharing=await(await page.request.get(`/api/hestia/folders/${destination.id}/sharing`)).json();const alex=sharing.members.find((member:{name:string})=>member.name==="Alex");expect((await page.request.post(`/api/hestia/folders/${destination.id}/sharing`,{headers,data:{memberId:alex.id,export:false,deposit:false,modify:false,delete:false,idempotencyKey:randomUUID()}})).ok()).toBe(true);
  await panel.getByRole("button",{name:"Déplacer ici",exact:true}).click();await expect(panel.getByText("Effets modifiés.",{exact:true})).toBeVisible();expect(await parent(page.request,source.id)).toBeNull();await expect(panel.getByRole("region",{name:"Gagnent un accès"})).toContainText("Alex");await panel.getByRole("button",{name:"Déplacer ici",exact:true}).click();await expect(page.getByText("Déplacé.",{exact:true})).toBeVisible();expect(await parent(page.request,source.id)).toBe(destination.id);
});

test("réponse perdue : réconciliation avec le corps exact, aucun second déplacement",async({page})=>{
  const{source,destination}=await tree(page);let posts=0;let body:Record<string,unknown>|undefined;let reconciled:Record<string,unknown>|undefined;
  await page.route("**/api/hestia/moves",async route=>{posts++;body=route.request().postDataJSON();const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort("failed");});
  await page.route("**/api/hestia/move-operations/*",async route=>{reconciled=route.request().postDataJSON();await route.continue();});
  await start(page);const reviewPanel=await pick(page,destination);await reviewPanel.getByRole("button",{name:"Déplacer ici",exact:true}).click();const panel=page.getByRole("complementary",{name:"Déplacement",exact:true});await expect(panel.getByText("Résultat incertain.",{exact:true})).toBeVisible();await expect(panel.getByRole("button",{name:"Déplacer ici",exact:true})).toHaveCount(0);await expect(panel.getByRole("button",{name:"Fermer",exact:true})).toBeDisabled();await panel.getByRole("button",{name:"Vérifier le résultat",exact:true}).click();await expect(page.getByText("Déplacé.",{exact:true})).toBeVisible();expect(posts).toBe(1);const semantic={...body};delete semantic.idempotencyKey;expect(reconciled).toEqual(semantic);expect(await parent(page.request,source.id)).toBe(destination.id);
});

test("révocation connue efface le panneau et la saisie de destination",async({page,browser,isMobile})=>{
  const{source,destination}=await tree(page);const sharing=await(await page.request.get(`/api/hestia/folders/${source.id}/sharing`)).json();const alex=sharing.members.find((member:{name:string})=>member.name==="Alex");for(const folder of[source,destination])expect((await page.request.post(`/api/hestia/folders/${folder.id}/sharing`,{headers,data:{memberId:alex.id,export:false,deposit:false,modify:true,delete:false,idempotencyKey:randomUUID()}})).ok()).toBe(true);
  const context=await browser.newContext({baseURL:"http://127.0.0.1:3210",viewport:page.viewportSize(),isMobile,hasTouch:isMobile});try{const receiver=await context.newPage();await login(receiver,"alex");await receiver.getByRole("main").getByRole("button",{name:new RegExp(source.name)}).click();await start(receiver);await pick(receiver,destination);const access=await(await page.request.get(`/api/hestia/folders/${source.id}/access`)).json();const grant=access.grants.find((entry:{memberId:string;canRevoke:boolean})=>entry.memberId===alex.id&&entry.canRevoke);expect((await page.request.delete(`/api/hestia/folders/${source.id}/access/${grant.id}`,{headers})).ok()).toBe(true);const refreshed=receiver.waitForResponse(response=>response.url().endsWith("/api/hestia/folders")&&response.request().method()==="GET");await receiver.bringToFront();await receiver.evaluate(()=>window.dispatchEvent(new Event("focus")));await refreshed;await expect(receiver.getByRole("complementary",{name:/^Déplacer/})).toHaveCount(0);await expect(receiver.getByText(source.name,{exact:false})).toHaveCount(0);}finally{await context.close();}
});

test("effets différents dans les descendants : détails accessibles et noms bornés à l’aperçu",async({page})=>{
  const{source,destination}=await tree(page);const safeDetail="Branche autorisée";
  // This isolates the real rendered AccessImpact contract. Backend disclosure and
  // subtree authorization are independently exercised by SQL/HTTP tests.
  await page.route("**/api/hestia/move-preview",async route=>{const response=await route.fetch();expect(response.ok()).toBe(true);const preview=await response.json();await route.fulfill({response,json:{...preview,impactNote:"Les personnes qui ne sont pas listées gardent les mêmes droits.",groups:[{icon:"folder-open",title:"Changements dans une partie du contenu seulement",lead:"Les accès au dossier lui-même ne changent pas.",items:[{name:"Alex",text:"des droits changent dans certains éléments du contenu.",details:[{text:"Dans 1 élément : gagne : consulter",folders:[safeDetail]}]}]}]}});});
  await start(page);const panel=await pick(page,destination);await expect(panel.getByText(safeDetail,{exact:true})).toHaveCount(0);const expand=panel.getByRole("button",{name:/Voir les effets différents/});await expand.focus();await page.keyboard.press("Enter");await expect(panel.getByRole("region",{name:"Effets différents pour Alex"})).toContainText(safeDetail);await expect(panel.getByRole("button",{name:/Masquer les effets différents/})).toHaveAttribute("aria-expanded","true");await page.screenshot({path:test.info().outputPath("move-impact-details.png"),fullPage:true});await panel.getByRole("button",{name:"Annuler",exact:true}).click();expect(await parent(page.request,source.id)).toBeNull();
});

test("destination révoquée : un inventaire frais retire aussi ses anciens détails de confirmation",async({page,browser,isMobile})=>{
  const{source,destination}=await tree(page);const sharing=await(await page.request.get(`/api/hestia/folders/${source.id}/sharing`)).json();const alex=sharing.members.find((member:{name:string})=>member.name==="Alex");for(const folder of[source,destination])expect((await page.request.post(`/api/hestia/folders/${folder.id}/sharing`,{headers,data:{memberId:alex.id,export:false,deposit:false,modify:true,delete:false,idempotencyKey:randomUUID()}})).ok()).toBe(true);
  const context=await browser.newContext({baseURL:"http://127.0.0.1:3210",viewport:page.viewportSize(),isMobile,hasTouch:isMobile});try{const receiver=await context.newPage();await login(receiver,"alex");await receiver.getByRole("main").getByRole("button",{name:new RegExp(source.name)}).click();await start(receiver);const panel=await pick(receiver,destination);await expect(panel.getByText(destination.name,{exact:true})).toBeVisible();const access=await(await page.request.get(`/api/hestia/folders/${destination.id}/access`)).json();const grant=access.grants.find((entry:{memberId:string;canRevoke:boolean})=>entry.memberId===alex.id&&entry.canRevoke);expect((await page.request.delete(`/api/hestia/folders/${destination.id}/access/${grant.id}`,{headers})).ok()).toBe(true);const refreshed=receiver.waitForResponse(response=>response.url().endsWith("/api/hestia/folders")&&response.request().method()==="GET");await receiver.bringToFront();await receiver.evaluate(()=>window.dispatchEvent(new Event("focus")));await refreshed;await expect(receiver.getByText(destination.name,{exact:false})).toHaveCount(0);await expect(panel.getByRole("radiogroup",{name:"Destination"})).toBeVisible();await expect(panel.getByRole("button",{name:"Déplacer ici",exact:true})).toHaveCount(0);}finally{await context.close();}
});

test("un inventaire inchangé conserve l’aperçu et sa confirmation",async({page})=>{
  const{source,destination}=await tree(page);await start(page);const panel=await pick(page,destination);await expect(panel.getByRole("button",{name:"Déplacer ici",exact:true})).toBeVisible();
  const refreshed=page.waitForResponse(response=>response.url().endsWith("/api/hestia/folders")&&response.request().method()==="GET");await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await refreshed;
  await expect(panel.getByRole("button",{name:"Déplacer ici",exact:true})).toBeVisible();await panel.getByRole("button",{name:"Annuler",exact:true}).click();expect(await parent(page.request,source.id)).toBeNull();
});

test("document déplacé hors droits avec compteur compensé : le titre privé disparaît malgré inventaire identique",async({page,browser,isMobile})=>{
  const{source,destination,suffix}=await tree(page);const hidden=await create(page.request,`Privé ${suffix}`);const lost=await upload(page.request,source,`Titre secret ${suffix}`);const replacement=await upload(page.request,hidden,`Remplacement ${suffix}`);const sharing=await(await page.request.get(`/api/hestia/folders/${source.id}/sharing`)).json();const alex=sharing.members.find((member:{name:string})=>member.name==="Alex");await share(page.request,source,alex.id);await share(page.request,destination,alex.id);
  const context=await browser.newContext({baseURL:"http://127.0.0.1:3210",viewport:page.viewportSize(),isMobile,hasTouch:isMobile});try{const receiver=await context.newPage();await login(receiver,"alex");await receiver.getByRole("main").getByRole("button",{name:new RegExp(source.name)}).click();await receiver.getByRole("main").getByRole("button",{name:new RegExp(lost.title)}).click();await receiver.getByRole("complementary",{name:"Document",exact:true}).getByRole("button",{name:"Déplacer…",exact:true}).click();await expect(receiver.getByRole("complementary",{name:`Déplacer « ${lost.title} »`,exact:true})).toBeVisible();const before=await(await receiver.request.get("/api/hestia/folders")).json();await moveApi(page.request,"document",lost.id,hidden.id);await moveApi(page.request,"document",replacement.id,source.id);const after=await(await receiver.request.get("/api/hestia/folders")).json();expect(after).toEqual(before);const refreshed=receiver.waitForResponse(response=>response.url().endsWith(`/api/hestia/documents/${lost.id}`));await receiver.bringToFront();await receiver.evaluate(()=>window.dispatchEvent(new Event("focus")));expect((await refreshed).status()).toBe(404);await expect(receiver.getByText(lost.title,{exact:false})).toHaveCount(0);await expect(receiver.getByRole("complementary",{name:/^Déplacer/})).toHaveCount(0);}finally{await context.close();}
});

test("réponse d’aperçu tardive après révocation : aucune destination privée ne revient",async({page,browser,isMobile})=>{
  const{source,destination}=await tree(page);const sharing=await(await page.request.get(`/api/hestia/folders/${source.id}/sharing`)).json();const alex=sharing.members.find((member:{name:string})=>member.name==="Alex");await share(page.request,source,alex.id);await share(page.request,destination,alex.id);
  const context=await browser.newContext({baseURL:"http://127.0.0.1:3210",viewport:page.viewportSize(),isMobile,hasTouch:isMobile});let release!:()=>void;const hold=new Promise<void>(resolve=>{release=resolve;});let ready!:()=>void;const requested=new Promise<void>(resolve=>{ready=resolve;});let delivered!:()=>void;const delivery=new Promise<void>(resolve=>{delivered=resolve;});try{const receiver=await context.newPage();await login(receiver,"alex");await receiver.route("**/api/hestia/move-preview",async route=>{const response=await route.fetch();ready();await hold;try{await route.fulfill({response});}catch{/* The application may already have aborted this obsolete request. */}finally{delivered();}});await receiver.getByRole("main").getByRole("button",{name:new RegExp(source.name)}).click();await start(receiver);const panel=await pick(receiver,destination);await requested;const access=await(await page.request.get(`/api/hestia/folders/${destination.id}/access`)).json();const grant=access.grants.find((entry:{memberId:string;canRevoke:boolean})=>entry.memberId===alex.id&&entry.canRevoke);expect((await page.request.delete(`/api/hestia/folders/${destination.id}/access/${grant.id}`,{headers})).ok()).toBe(true);const refreshed=receiver.waitForResponse(response=>response.url().endsWith("/api/hestia/folders")&&response.request().method()==="GET");await receiver.bringToFront();await receiver.evaluate(()=>window.dispatchEvent(new Event("focus")));await refreshed;await expect(receiver.getByText(destination.name,{exact:false})).toHaveCount(0);release();await delivery;await expect(panel.getByRole("radiogroup",{name:"Destination"})).toBeVisible();await expect(receiver.getByText(destination.name,{exact:false})).toHaveCount(0);await expect(panel.getByRole("button",{name:"Déplacer ici",exact:true})).toHaveCount(0);}finally{release();await context.close();}
});

test("réponse perdue avec perte de lecture par le déplacement : reçu retrouvé sans titre privé",async({page,browser,isMobile})=>{
  const{source,suffix}=await tree(page);const child=await create(page.request,`Extrait ${suffix}`,source.id);const sharing=await(await page.request.get(`/api/hestia/folders/${source.id}/sharing`)).json();const alex=sharing.members.find((member:{name:string})=>member.name==="Alex");await share(page.request,source,alex.id);const endpoint=`/api/hestia/folders/${child.id}/management-transfer`;const proposal=await(await page.request.get(endpoint)).json();expect((await page.request.post(endpoint,{headers,data:{idempotencyKey:randomUUID(),referenceId:proposal.referenceId,nomineeId:alex.id,reviewVersion:proposal.reviewVersion}})).ok()).toBe(true);
  const context=await browser.newContext({baseURL:"http://127.0.0.1:3210",viewport:page.viewportSize(),isMobile,hasTouch:isMobile});try{const receiver=await context.newPage();await login(receiver,"alex");await receiver.getByRole("main").getByRole("button",{name:new RegExp(source.name)}).click();await receiver.getByRole("main").getByRole("button",{name:new RegExp(child.name)}).click();let posts=0;await receiver.route("**/api/hestia/moves",async route=>{posts++;const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort("failed");});const panel=await start(receiver);await panel.getByRole("button",{name:"Tous les dossiers",exact:true}).click();await panel.getByRole("radio",{name:"À la racine (Dossiers)",exact:true}).click();await panel.getByRole("button",{name:"Vérifier les effets",exact:true}).click();await panel.getByRole("button",{name:"Déplacer ici",exact:true}).click();await expect(receiver.getByText("Résultat incertain.",{exact:true})).toBeVisible();const refreshed=receiver.waitForResponse(response=>response.url().endsWith("/api/hestia/folders")&&response.request().method()==="GET");await receiver.evaluate(()=>window.dispatchEvent(new Event("focus")));await refreshed;await expect(receiver.getByText(child.name,{exact:false})).toHaveCount(0);const recovery=receiver.getByRole("complementary",{name:"Déplacement",exact:true});await recovery.getByRole("button",{name:"Vérifier le résultat",exact:true}).click();await expect(receiver.getByText("Déplacé.",{exact:true})).toBeVisible();expect(posts).toBe(1);expect((await receiver.request.get(`/api/hestia/folders/${child.id}`)).status()).toBe(404);}finally{await context.close();}
});

test("changement d’acteur observé : ancien aperçu supprimé même pour un dossier encore partagé",async({page})=>{
  const{source,destination}=await tree(page);const sharing=await(await page.request.get(`/api/hestia/folders/${source.id}/sharing`)).json();const alex=sharing.members.find((member:{name:string})=>member.name==="Alex");await share(page.request,source,alex.id);await share(page.request,destination,alex.id);await page.reload();await page.getByRole("main").getByRole("button",{name:new RegExp(source.name)}).click();await start(page);const panel=await pick(page,destination);await expect(panel.getByText("Destination",{exact:true})).toBeVisible();expect((await page.request.post("/api/auth/sign-out",{headers,data:{}})).ok()).toBe(true);let signedIn=false;for(let attempt=0;attempt<4;attempt++){const response=await page.request.post("/api/auth/sign-in/email",{headers,data:{email:"alex@hestia.invalid",password}});if(response.status()!==429){expect(response.ok()).toBe(true);signedIn=true;break;}await page.waitForTimeout(10_100);}expect(signedIn).toBe(true);const refreshed=page.waitForResponse(result=>result.url().endsWith("/api/hestia/folders")&&result.request().method()==="GET");await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await refreshed;await expect(page.getByRole("complementary",{name:/^Déplacer/})).toHaveCount(0);await expect(page.getByText("Effets sur les accès",{exact:true})).toHaveCount(0);
});
