"use client";

import { useEffect, useRef, useState, type CSSProperties } from "react";
import { Button, Icon } from "./design-system";

export type TreeFolder = { id: string; name: string; createdAt: string; createdByName: string; version: number; capabilities: string[]; documentCount: number; childCount: number; visibleParentId: string | null; breadcrumbs: {id: string; name: string}[]; canShare?: boolean; canAdminister?: boolean };

// Technical port of Clé de voûte 1.3 FolderPath and the validated 1.0 Menu.
// All path items are filtered by the server before they reach this component.
export function FolderPath({ folder, onFolder, onRoot }: {folder: TreeFolder; onFolder: (id: string) => void; onRoot: () => void}) {
  const [open, setOpen] = useState(false);
  const [compact, setCompact] = useState(false);
  const [hoverPath, setHoverPath] = useState(false);
  useEffect(() => { const media = window.matchMedia("(max-width: 599px)"); const update = () => setCompact(media.matches); update(); media.addEventListener("change", update); return () => media.removeEventListener("change", update); }, []);
  const items = [{id: "root", name: "Dossiers"}, ...folder.breadcrumbs];
  const go = (id: string) => { setOpen(false); if (id === "root") onRoot(); else onFolder(id); };
  const link: CSSProperties = {border: 0, background: "transparent", padding: "4px 2px", minHeight: 32, cursor: "pointer", fontFamily: "var(--cdv-font-text)", fontSize: 14, color: "var(--cdv-ink-2)", textDecoration: "underline", textUnderlineOffset: 3, maxWidth: 220, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", borderRadius: "var(--cdv-radius-s)"};
  const shown = items.length <= 5 ? items : [items[0], null, ...items.slice(-3)];
  const parent = items[items.length - 2];
  return <div style={{display:"flex",flexDirection:"column"}} onKeyDown={event => { if (event.key === "Escape") setOpen(false); }}>
    {compact ? <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8}}><Button variant="tertiary" compact icon="chevron-left" aria-label={`Revenir à « ${parent.name} »`} onClick={() => go(parent.id)}>{parent.name.length > 26 ? parent.name.slice(0,25).trim() + "…" : parent.name}</Button>{items.length > 2 && <button type="button" className="cdv-focus" aria-expanded={open} aria-label={open ? "Masquer le chemin complet" : `Afficher le chemin complet (${items.length} niveaux)`} onClick={() => setOpen(!open)} onMouseEnter={()=>setHoverPath(true)} onMouseLeave={()=>setHoverPath(false)} style={{width:44,height:44,display:"inline-flex",alignItems:"center",justifyContent:"center",borderRadius:"var(--cdv-radius-m)",cursor:"pointer",background:hoverPath?"var(--cdv-action-tint)":"transparent",border:"1.5px solid transparent",color:hoverPath?"var(--cdv-action-hover)":"var(--cdv-ink)",transition:"background var(--cdv-duration) var(--cdv-ease)"}}><Icon name="list-tree" size={20}/></button>}</div> : <nav aria-label="Fil d’Ariane" style={{display:"flex",alignItems:"center",gap:6,flexWrap:"wrap",fontSize:14,color:"var(--cdv-ink-3)"}}>{shown.map((item, index) => <span key={item?.id ?? "gap"} style={{display:"flex",alignItems:"center",gap:6,minWidth:0}}>{!item ? <button className="cdv-focus" type="button" aria-expanded={open} aria-label={`Afficher les ${items.length - 4} niveaux intermédiaires`} onClick={() => setOpen(!open)} style={{...link,textDecoration:"none",fontWeight:700,padding:"4px 8px",border:"1.5px solid var(--cdv-border)"}}>…</button> : item.id === folder.id ? <span aria-current="page" title={item.name} style={{color:"var(--cdv-ink)",fontWeight:700,maxWidth:260,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{item.name}</span> : <button type="button" className="cdv-focus" title={item.name} style={link} onClick={() => go(item.id)}>{item.name}</button>}{index < shown.length - 1 && <Icon name="chevron-right" size={14}/>}</span>)}</nav>}
    {open && <nav aria-label="Chemin complet" style={{padding:8,marginTop:8,background:"var(--cdv-surface)",border:"1.5px solid var(--cdv-border)",borderRadius:"var(--cdv-radius-l)",boxShadow:"var(--cdv-shadow-card)"}}><ol style={{listStyle:"none",margin:0,padding:0,display:"flex",flexDirection:"column",gap:2}}>{items.map((item, index) => <li key={item.id} style={{paddingLeft:Math.min(index,6)*12}}>{item.id === folder.id ? <span aria-current="page" style={{display:"flex",alignItems:"center",gap:8,minHeight:44,padding:"0 10px",fontWeight:700,fontSize:15,overflowWrap:"anywhere"}}><Icon name="folder-open" size={18}/>{item.name}</span> : <button type="button" className="cdv-focus" onClick={() => go(item.id)} style={{display:"flex",alignItems:"center",gap:8,width:"100%",minHeight:44,padding:"0 10px",border:0,borderRadius:"var(--cdv-radius-m)",background:"transparent",cursor:"pointer",textAlign:"left",fontFamily:"var(--cdv-font-text)",fontSize:15,color:"var(--cdv-ink)",overflowWrap:"anywhere"}}><Icon name={index ? "folder" : "home"} size={18}/>{item.name}</button>}</li>)}</ol></nav>}
  </div>;
}

export function FolderActions({ onRename, onAccess }: {onRename?: () => void; onAccess?: () => void}) {
  const [open, setOpen] = useState(false); const [index, setIndex] = useState(0);
  const root = useRef<HTMLDivElement>(null); const trigger = useRef<HTMLButtonElement>(null);
  const items = [...(onRename ? [{label:"Renommer",icon:"pencil",run:onRename}] : []), ...(onAccess ? [{label:"Voir les accès",icon:"users",run:onAccess}] : [])];
  useEffect(() => { if (open) root.current?.querySelector<HTMLButtonElement>('[role="menuitem"]')?.focus(); }, [open]);
  if (!items.length) return null;
  return <div ref={root} style={{position:"relative"}} onBlur={event => { if (!event.currentTarget.contains(event.relatedTarget)) setOpen(false); }} onKeyDown={event => { if (event.key === "Escape") { setOpen(false); trigger.current?.focus(); } }}><button ref={trigger} type="button" className="cdv-focus h-button h-button-secondary" aria-expanded={open} aria-haspopup="menu" onClick={() => setOpen(!open)}><Icon name="more" size={18}/><span>Actions</span></button>{open && <div role="menu" aria-label="Actions sur le dossier" onKeyDown={event => { if (!["ArrowDown","ArrowUp","Home","End"].includes(event.key)) return; event.preventDefault(); const next=event.key === "Home" ? 0 : event.key === "End" ? items.length-1 : (index+(event.key === "ArrowDown" ? 1 : -1)+items.length)%items.length; setIndex(next); root.current?.querySelectorAll<HTMLButtonElement>('[role="menuitem"]')[next]?.focus(); }} style={{position:"absolute",top:52,left:0,zIndex:40,width:260,padding:6,border:"1.5px solid var(--cdv-border)",borderRadius:"var(--cdv-radius-l)",background:"var(--cdv-surface)",boxShadow:"var(--cdv-shadow-float)",display:"flex",flexDirection:"column",gap:2,fontSize:16,boxSizing:"border-box"}}>{items.map((item,i) => <button key={item.label} type="button" role="menuitem" className="cdv-focus" tabIndex={index===i?0:-1} onFocus={() => setIndex(i)} onClick={() => { setOpen(false); item.run(); }} style={{height:44,padding:"0 12px",borderRadius:"var(--cdv-radius-m)",display:"flex",alignItems:"center",gap:12,border:0,background:index===i?"var(--cdv-action-tint)":"transparent",color:index===i?"var(--cdv-action-hover)":"var(--cdv-ink)",cursor:"pointer",textAlign:"left",font:"inherit",fontWeight:index===i?700:400}}><Icon name={item.icon} size={18}/>{item.label}</button>)}</div>}</div>;
}
