import {randomUUID} from 'node:crypto';
import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
import {Pool} from 'pg';
import {createApplication} from '../../src/server/application';
import {createAccess} from '../../src/server/access';
import {createAuth} from '../../src/server/auth/options';
import {readServerConfig} from '../../src/server/config';
import {migrateDatabase} from '../../src/server/db/migrate';
import {provisionSyntheticMember} from '../../src/server/db/synthetic';
import {getFolderAccess,issueGrant} from '../../src/server/permissions/service';

describe('inherited management transfer and succession on real PostgreSQL',()=>{
 const config=readServerConfig();if(config.environment!=='local'||!/^\/hestia_test_[a-z0-9_]+$/.test(new URL(config.databaseUrl).pathname)||!/^hestia-app-[a-f0-9]{16}$/.test(process.env.HESTIA_TEST_RUN_ID??''))throw Error('Owned synthetic bench required');
 const pool=new Pool({connectionString:config.databaseUrl,max:8}),app=createApplication(pool,config),access=createAccess(pool,config,createAuth(pool,config));
 const users:{id:string;email:string;cookie:string}[]=[],password='Synthetic tree management phrase!';let root:string,child:string,leaf:string,sibling:string,reference:string;
 function req(body?:unknown,user=0,method?:string){return new Request(config.origin+'/api/hestia/test',{method:method??(body===undefined?'GET':'POST'),headers:{origin:config.origin,cookie:users[user]?.cookie??'',...(body===undefined?{}:{'content-type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});}
 async function create(parentId?:string){const r=await app.handleFolders(req({name:`Management ${randomUUID()}`,...(parentId?{parentId}:{}),idempotencyKey:randomUUID()}));expect(r.status).toBe(201);return (await r.json()).folder.id as string;}
 async function rights(user:number,folder=leaf){return access.transaction(async c=>(await getFolderAccess(c,users[user].id,folder)).capabilities);}
 async function grant(user:number,folder=root){return access.transaction(c=>issueGrant(c,users[0].id,folder,{authorityId:reference,subject:users[user].id,capability:'consulter'}));}
 async function transfer(folder=child,actor=0,nominee=1){const r=await app.handleManagementTransfer(req(undefined,actor),folder);expect(r.status).toBe(200);const preview=await r.json();return {idempotencyKey:randomUUID(),referenceId:preview.referenceId,nomineeId:users[nominee].id,reviewVersion:preview.reviewVersion};}
 beforeAll(async()=>{expect((await pool.query("SELECT to_regclass('hestia_bench_marker') AS marker")).rows[0].marker).toBeTruthy();await migrateDatabase(pool,config);for(let i=0;i<4;i++){const email=`tree-management-${randomUUID()}@example.invalid`,id=await provisionSyntheticMember(pool,{email,name:`Tree manager ${i}`,password,role:i===3?'admin':'member'});users.push({id,email,cookie:''});}});
 beforeEach(async()=>{await pool.query('UPDATE hestia_member SET active=true WHERE user_id=ANY($1::text[])',[users.map(u=>u.id)]);for(const u of users){await pool.query('UPDATE "rateLimit" SET "lastRequest"=0');const r=await app.handleAuth(new Request(config.origin+'/api/auth/sign-in/email',{method:'POST',headers:{origin:config.origin,'content-type':'application/json'},body:JSON.stringify({email:u.email,password})}));expect(r.status).toBe(200);u.cookie=r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');}root=await create();child=await create(root);leaf=await create(child);sibling=await create(root);reference=(await pool.query('SELECT reference_grant_id FROM hestia_folder WHERE id=$1',[root])).rows[0].reference_grant_id;await grant(1);});
 afterAll(async()=>{await pool.end();});
 it('transfers inherited management only in the chosen subtree, preserving direct powers and siblings',async()=>{await grant(2,leaf);const input=await transfer();const r=await app.handleManagementTransfer(req(input),child);expect(r.status).toBe(200);expect((await app.handleManagementTransfer(req(input),child)).status).toBe(200);expect(await rights(0)).not.toContain('administrer');expect(await rights(0)).toContain('consulter');expect(await rights(0,sibling)).toContain('administrer');expect(await rights(1)).toContain('administrer');expect(await rights(2)).toEqual([]);const old=(await pool.query('SELECT revoked_at FROM hestia_grant WHERE id=$1',[reference])).rows[0];expect(old.revoked_at).toBeNull();const local=(await pool.query('SELECT g.* FROM hestia_folder f JOIN hestia_grant g ON g.id=f.reference_grant_id WHERE f.id=$1',[child])).rows[0];expect(local.origin).toBe('reference-inherited-transfer');expect(local.anchor_reference_id).toBe(reference);expect(local.parent_id).toBeNull();expect((await pool.query('SELECT count(*)::int n FROM hestia_management_cut WHERE folder_id=$1',[child])).rows[0].n).toBe(1);});
 it('does not nominate a reader whose only access depends on the inherited reference being cut',async()=>{await grant(2,child);const r=await app.handleManagementTransfer(req(),child);expect(r.status).toBe(200);const p=await r.json();expect(p.eligible.map((m:{id:string})=>m.id)).not.toContain(users[2].id);expect((await app.handleManagementTransfer(req({idempotencyKey:randomUUID(),referenceId:p.referenceId,nomineeId:users[2].id,reviewVersion:p.reviewVersion}),child)).status).toBe(409);expect((await pool.query('SELECT reference_grant_id FROM hestia_folder WHERE id=$1',[child])).rows[0].reference_grant_id).toBeNull();});
 it('refuses a surviving reader restricted from administration and preserves the original management frame',async()=>{expect((await app.handleFolderRestriction(req({memberId:users[1].id,capabilities:['administrer'],restricted:true}),child)).status).toBe(200);const r=await app.handleManagementTransfer(req(),child);expect(r.status).toBe(200);const p=await r.json();expect(p.eligible.map((m:{id:string})=>m.id)).not.toContain(users[1].id);expect((await app.handleManagementTransfer(req({idempotencyKey:randomUUID(),referenceId:p.referenceId,nomineeId:users[1].id,reviewVersion:p.reviewVersion}),child)).status).toBe(409);expect(await rights(0)).toContain('administrer');expect((await pool.query('SELECT reference_grant_id FROM hestia_folder WHERE id=$1',[child])).rows[0].reference_grant_id).toBeNull();});
 it('does not orphan a descendant where the otherwise eligible nominee cannot administer',async()=>{expect((await app.handleFolderRestriction(req({memberId:users[1].id,capabilities:['administrer'],restricted:true}),leaf)).status).toBe(200);const r=await app.handleManagementTransfer(req(),child);expect(r.status).toBe(200);const p=await r.json();expect(p.eligible.map((m:{id:string})=>m.id)).not.toContain(users[1].id);expect(await rights(0)).toContain('administrer');});
 it('preserves an independent child management frame when the root reference is later replaced',async()=>{await grant(2);expect((await app.handleManagementTransfer(req(await transfer()),child)).status).toBe(200);expect((await app.handleManagementTransfer(req(await transfer(root,0,2)),root)).status).toBe(200);expect(await rights(2,root)).toContain('administrer');expect(await rights(2,sibling)).toContain('administrer');expect(await rights(2)).not.toContain('administrer');expect(await rights(2)).toContain('consulter');expect(await rights(1)).toContain('administrer');});
 it('does not nominate a surviving reader whose restriction would leave part of the vacant inherited frame unmanaged',async()=>{await grant(2);expect((await app.handleManagementTransfer(req(await transfer()),child)).status).toBe(200);expect((await app.handleFolderRestriction(req({memberId:users[2].id,capabilities:['administrer'],restricted:true},1),leaf)).status).toBe(200);await pool.query('UPDATE hestia_member SET active=false WHERE user_id=$1',[users[1].id]);const response=await app.handleSuccessionPreview(req(undefined,3),child);expect(response.status).toBe(200);const p=await response.json();expect(p.eligible.map((m:{id:string})=>m.id)).not.toContain(users[2].id);expect((await app.handleNominateSuccessor(req({idempotencyKey:randomUUID(),previousReferenceId:p.previousReferenceId,nomineeId:users[2].id,reviewVersion:p.reviewVersion},3),child)).status).toBe(409);});
 it('does not require repairing an autonomous nested vacancy before nominating the surrounding frame',async()=>{await grant(2);expect((await app.handleManagementTransfer(req(await transfer(leaf,0,2)),leaf)).status).toBe(200);expect((await app.handleManagementTransfer(req(await transfer()),child)).status).toBe(200);await pool.query('UPDATE hestia_member SET active=false WHERE user_id=ANY($1::text[])',[[users[1].id,users[2].id]]);const response=await app.handleSuccessionPreview(req(undefined,3),child);expect(response.status).toBe(200);const p=await response.json();expect(p.eligible.map((m:{id:string})=>m.id)).toContain(users[0].id);expect((await app.handleNominateSuccessor(req({idempotencyKey:randomUUID(),previousReferenceId:p.previousReferenceId,nomineeId:users[0].id,reviewVersion:p.reviewVersion},3),child)).status).toBe(200);expect(await rights(0,child)).toContain('administrer');expect(await rights(0,leaf)).not.toContain('administrer');const nested=(await pool.query('SELECT g.user_id,g.revoked_at FROM hestia_folder f JOIN hestia_grant g ON g.id=f.reference_grant_id WHERE f.id=$1',[leaf])).rows[0];expect(nested.user_id).toBe(users[2].id);expect(nested.revoked_at).not.toBeNull();});
 it('preserves the inherited expiry and refuses a stale preview after restriction',async()=>{const expiry=new Date(Date.now()+3600000);await pool.query('UPDATE hestia_grant SET expires_at=$2 WHERE id=$1',[reference,expiry]);const input=await transfer();expect((await app.handleFolderRestriction(req({memberId:users[2].id,capabilities:['exporter'],restricted:true}),leaf)).status).toBe(200);expect((await app.handleManagementTransfer(req(input),child)).status).toBe(409);const current=await transfer();expect((await app.handleManagementTransfer(req(current),child)).status).toBe(200);expect((await pool.query('SELECT g.expires_at FROM hestia_folder f JOIN hestia_grant g ON g.id=f.reference_grant_id WHERE f.id=$1',[child])).rows[0].expires_at.toISOString()).toBe(expiry.toISOString());});
 it('invalidates descendant access effects when only server time changes after the preview',async()=>{await grant(2,leaf);await pool.query(`INSERT INTO hestia_grant(id,folder_id,user_id,capability,kind,author_id,subject_epoch,expires_at)
   VALUES($1,$2,$3,'consulter','direct',$4,(SELECT departure_epoch FROM hestia_member WHERE user_id=$3),clock_timestamp()+interval '3 seconds')`,[randomUUID(),leaf,users[2].id,users[0].id]);const first=await app.handleManagementTransfer(req(),child);expect(first.status).toBe(200);const p=await first.json();expect(p.lostReaders.map((m:{id:string})=>m.id)).not.toContain(users[2].id);await new Promise(resolve=>setTimeout(resolve,3100));const second=await app.handleManagementTransfer(req(),child);expect(second.status).toBe(200);const updated=await second.json();expect(updated.lostReaders.map((m:{id:string})=>m.id)).toContain(users[2].id);expect(updated.reviewVersion).not.toBe(p.reviewVersion);expect((await app.handleManagementTransfer(req({idempotencyKey:randomUUID(),referenceId:p.referenceId,nomineeId:users[1].id,reviewVersion:p.reviewVersion}),child)).status).toBe(409);expect((await pool.query('SELECT reference_grant_id FROM hestia_folder WHERE id=$1',[child])).rows[0].reference_grant_id).toBeNull();});
 it('succeeds an inherited-transfer reference after departure without granting the household admin document access',async()=>{await grant(2);expect((await app.handleManagementTransfer(req(await transfer()),child)).status).toBe(200);await pool.query('UPDATE hestia_member SET active=false WHERE user_id=$1',[users[1].id]);const preview=await app.handleSuccessionPreview(req(undefined,3),child);expect(preview.status).toBe(200);const p=await preview.json();expect(p.folder.title).toBeUndefined();expect(p.eligible.map((m:{id:string})=>m.id)).toContain(users[2].id);expect((await app.handleNominateSuccessor(req({idempotencyKey:randomUUID(),previousReferenceId:p.previousReferenceId,nomineeId:users[2].id,reviewVersion:p.reviewVersion},3),child)).status).toBe(200);expect(await rights(2)).toContain('administrer');expect(await rights(3)).toEqual([]);expect(await rights(0,sibling)).toContain('administrer');});
});
