import {describe,it,expect} from 'vitest';
import {evaluateTreeAccess,type AccessGraph} from '../../src/server/permissions/tree';
import type {Grant} from '../../src/server/permissions/service';
import {CAPABILITIES} from '../../src/server/permissions/capabilities';
import {folderNameKey} from '../../src/server/db/folder-name';

const grant=(id:string,user_id:string,capability:string,folder_id='root',extra:Partial<Grant>={}):Grant=>({id,user_id,capability,folder_id,kind:'direct',parent_id:null,transmit:[],lineage:[],origin:'initial',author_id:'a',subject_epoch:0,revoked_at:null,expires_at:null,batch_id:null,created_at:new Date(0),...extra});
function fixture():AccessGraph{return {now:1000,folders:[{id:'root',created_by:'a',parent_folder_id:null},{id:'child',created_by:'b',parent_folder_id:'root'},{id:'leaf',created_by:'b',parent_folder_id:'child'},{id:'sibling',created_by:'a',parent_folder_id:'root'},{id:'other',created_by:'d',parent_folder_id:null}],members:['a','b','c','d'].map(user_id=>({user_id,name:user_id,active:true,departure_epoch:0})),restrictions:[],grants:[grant('ref','a','administrer','root',{kind:'reference',transmit:[...CAPABILITIES]}),grant('read-a','a','consulter'),grant('read-b','b','consulter'),grant('modify-b','b','modifier')]};}
const read=(g:AccessGraph,actor='b',folder='leaf')=>evaluateTreeAccess(g,actor,folder);
const restrict=(g:AccessGraph,user_id:string,capability:string,folder_id='child')=>g.restrictions.push({id:`${user_id}:${capability}`,user_id,capability,folder_id,authority_grant_id:'ref',author_id:'a'});

describe('product tree authority graph',()=>{
 it('inherits live sources without inventing a creator grant or reference',()=>{const g=fixture(),state=read(g);expect(state.capabilities.sort()).toEqual(['consulter','modifier']);expect(state.rows).toEqual([]);expect(state.ownerId).toBe('b');expect(state.canAdminister).toBe(false);g.grants[2].revoked_at=new Date(900);expect(read(g).capabilities).toEqual(['modifier']);});
 it('lets an isolated local share contribute without exposing or authorizing ancestors',()=>{const g=fixture();g.grants.push(grant('isolated','c','consulter','leaf',{kind:'delegated',parent_id:'ref'}));expect(read(g,'c').capabilities).toEqual(['consulter']);expect(read(g,'c','root').capabilities).toEqual([]);expect(read(g,'c','child').capabilities).toEqual([]);});
 it('cuts targeted capabilities on every descendant and does not touch siblings',()=>{const g=fixture();restrict(g,'b','consulter');g.grants.push(grant('local-b','b','consulter','leaf'));expect(read(g).capabilities).toEqual(['modifier']);expect(read(g,'b','sibling').capabilities).toContain('consulter');});
 it('cuts a delegate when its issuer is restricted at the destination',()=>{const g=fixture();g.grants.push(grant('share-b','b','partager','root',{transmit:['consulter']}),grant('c-via-b','c','consulter','root',{kind:'delegated',parent_id:'share-b'}));expect(read(g,'c').capabilities).toContain('consulter');restrict(g,'b','partager');expect(read(g,'c').capabilities).toEqual([]);expect(read(g,'c','sibling').capabilities).toEqual(['consulter']);});
 it('checks issuer restrictions on the transmitted capability and at issuance context',()=>{const g=fixture();g.grants.push(grant('share-b','b','partager','child',{transmit:['consulter']}),grant('c-via-b','c','consulter','leaf',{kind:'delegated',parent_id:'share-b'}));restrict(g,'b','consulter');expect(read(g,'c').capabilities).toEqual([]);g.folders.find(f=>f.id==='leaf')!.parent_folder_id='other';expect(read(g,'c').capabilities).toEqual([]);});
 it('keeps an independent grant after a mandate disappears',()=>{const g=fixture();g.grants.push(grant('dependent','c','consulter','leaf',{kind:'delegated',parent_id:'ref'}),grant('independent','c','consulter','leaf'));g.grants[0].revoked_at=new Date(900);expect(read(g,'c').capabilities).toEqual(['consulter']);expect(read(g,'c').held.map(s=>s.id)).toEqual(['independent']);});
 it('propagates the ultimate capability across every intermediary at the target',()=>{const g=fixture();g.grants.push(grant('share-b','b','partager','child',{kind:'delegated',parent_id:'ref',transmit:['consulter']}),grant('read-c','c','consulter','leaf',{kind:'delegated',parent_id:'share-b'}));expect(read(g,'c').capabilities).toEqual(['consulter']);restrict(g,'a','consulter','leaf');expect(read(g,'b').authorityFor(['consulter'],'c')).toBeUndefined();expect(read(g,'c').capabilities).toEqual([]);expect(read(g,'b','child').authorityFor(['consulter'],'c')).toBeDefined();});
 it('retains all upstream restrictions in each immutable issuance context after placement changes',()=>{const g=fixture();g.grants.push(grant('share-b','b','partager','child',{kind:'delegated',parent_id:'ref',transmit:['consulter','partager']}),grant('share-c','c','partager','leaf',{kind:'delegated',parent_id:'share-b',transmit:['consulter']}));g.folders.push({id:'moved',created_by:'d',parent_folder_id:'leaf'});g.grants.push(grant('read-d','d','consulter','moved',{kind:'delegated',parent_id:'share-c'}));expect(read(g,'d','moved').capabilities).toEqual(['consulter']);restrict(g,'a','consulter','leaf');g.folders.find(f=>f.id==='moved')!.parent_folder_id='other';expect(read(g,'d','moved').capabilities).toEqual([]);});
 it('keeps a dependency after placement changes, and revokes it with that exact source',()=>{const g=fixture();g.grants.push(grant('dependent','c','consulter','leaf',{kind:'delegated',parent_id:'ref'}));g.folders.find(f=>f.id==='leaf')!.parent_folder_id='other';expect(read(g,'c').capabilities).toEqual(['consulter']);g.grants[0].revoked_at=new Date(900);expect(read(g,'c').capabilities).toEqual([]);});
 it('enforces expiry equality, membership epochs, and never aggregates separate envelopes',()=>{const g=fixture();g.grants.push(grant('share-one','b','partager','child',{transmit:['consulter','déposer'],expires_at:new Date(1001)}),grant('share-two','b','partager','child',{transmit:['consulter','exporter']}));expect(read(g).authorityFor(['consulter','déposer','exporter'],'c')).toBeUndefined();g.now=1001;expect(read(g).authorityFor(['consulter','déposer'],'c')).toBeUndefined();g.members[1].departure_epoch=1;expect(read(g).capabilities).toEqual([]);});
 it('cuts one management chain in a subtree but preserves independent and nested references',()=>{const g=fixture();g.grants.push(grant('dependent','c','consulter','child',{kind:'delegated',parent_id:'ref'}),grant('new-ref','b','administrer','child',{kind:'reference',transmit:[...CAPABILITIES]}),grant('nested-ref','d','administrer','leaf',{kind:'reference',transmit:['consulter']}));g.cuts=[{folder_id:'child',source_reference_id:'ref',new_reference_id:'new-ref'}];expect(read(g,'a').canAdminister).toBe(false);expect(read(g,'a','sibling').canAdminister).toBe(true);expect(read(g).canAdminister).toBe(true);expect(read(g,'d').canAdminister).toBe(true);expect(read(g,'c').capabilities).toEqual([]);expect(read(g,'a').capabilities).toEqual(['consulter']);});
 it('cannot revoke an inherited grant through a child scope',()=>{const g=fixture();expect(read(g,'a').canRevoke(g.grants[2])).toBe(false);expect(read(g,'a','root').canRevoke(g.grants[2])).toBe(true);});
 it('keeps a subtree frame cut after the source reference transfers or succeeds',()=>{const g=fixture();g.grants.push(grant('child-ref','b','administrer','child',{kind:'reference',transmit:[...CAPABILITIES],anchor_reference_id:'ref'}));g.cuts=[{folder_id:'child',source_reference_id:'ref',new_reference_id:'child-ref'}];g.grants[0].revoked_at=new Date(900);g.grants.push(grant('root-successor','c','administrer','root',{kind:'reference',transmit:[...CAPABILITIES],replaces_reference_id:'ref'}));expect(read(g,'c','root').canAdminister).toBe(true);expect(read(g,'c','sibling').canAdminister).toBe(true);expect(read(g,'c').canAdminister).toBe(false);expect(read(g,'b').canAdminister).toBe(true);});
 it('preserves an already autonomous nested frame when its surrounding inherited frame is later transferred',()=>{const g=fixture();g.grants.push(grant('leaf-ref','c','administrer','leaf',{kind:'reference',transmit:[...CAPABILITIES],anchor_reference_id:'ref'}),grant('child-ref','b','administrer','child',{kind:'reference',transmit:[...CAPABILITIES],anchor_reference_id:'ref'}));g.cuts=[{folder_id:'leaf',source_reference_id:'ref',new_reference_id:'leaf-ref'},{folder_id:'child',source_reference_id:'ref',new_reference_id:'child-ref'}];expect(read(g,'b','child').canAdminister).toBe(true);expect(read(g,'b').canAdminister).toBe(false);expect(read(g,'c').canAdminister).toBe(true);expect(read(g,'a','root').canAdminister).toBe(true);});
 it('handles deep placement iteratively and fails closed on cycles',()=>{const g=fixture();for(let i=0;i<300;i++)g.folders.push({id:`n${i}`,created_by:'a',parent_folder_id:i?`n${i-1}`:'leaf'});expect(read(g,'b','n299').capabilities).toContain('consulter');g.folders[0].parent_folder_id='n299';expect(read(g).capabilities).toEqual([]);});
 it('fails the whole request rather than silently truncating a graph budget',()=>{const g=fixture();g.folders=Array.from({length:10001},(_,i)=>({id:`n${i}`,created_by:'a',parent_folder_id:null}));expect(()=>read(g,'a','n0')).toThrow(expect.objectContaining({status:503,code:'RESOURCE_LIMIT'}));});
 it('normalizes folder names identically while preserving accents and internal spaces',()=>{expect(folderNameKey('  E\u0301TE  ')).toBe(folderNameKey('Éte'));expect(folderNameKey('Été')).not.toBe(folderNameKey('Ete'));expect(folderNameKey('A  B')).not.toBe(folderNameKey('A B'));});
});
